const dummyRideRequests = [
  {
    id: "1",
    userId: "john_doe",
    driverId: null,
    pickupLocation: { latitude: 37.78825, longitude: -122.4324 },
    destination: { latitude: 37.79825, longitude: -122.4224 },
    status: "pending",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "2",
    userId: "alice_smith",
    driverId: null,
    pickupLocation: { latitude: 37.728, longitude: -122.372 },
    destination: { latitude: 37.738, longitude: -122.382 },
    status: "pending",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "3",
    userId: "bob_jones",
    driverId: null,
    pickupLocation: { latitude: 37.758, longitude: -122.452 },
    destination: { latitude: 37.768, longitude: -122.462 },
    status: "pending",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "4",
    userId: "emma_davis",
    driverId: null,
    pickupLocation: { latitude: 37.768, longitude: -122.422 },
    destination: { latitude: 37.778, longitude: -122.432 },
    status: "picked-up",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "5",
    userId: "michael_brown",
    driverId: null,
    pickupLocation: { latitude: 37.798, longitude: -122.472 },
    destination: { latitude: 37.788, longitude: -122.462 },
    status: "accepted",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "6",
    userId: "sarah_taylor",
    driverId: null,
    pickupLocation: { latitude: 37.718, longitude: -122.402 },
    destination: { latitude: 37.728, longitude: -122.412 },
    status: "declined",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "7",
    userId: "william_clark",
    driverId: null,
    pickupLocation: { latitude: 37.748, longitude: -122.482 },
    destination: { latitude: 37.758, longitude: -122.472 },
    status: "dropped-off",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
];

export default dummyRideRequests;
