const dummyRideRequests = [
  {
    id: "1",
    userId: "user1",
    driverId: null,
    pickupLocation: { latitude: 37.78825, longitude: -122.4324 },
    destination: { latitude: 37.79825, longitude: -122.4224 },
    status: "pending",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "2",
    userId: "user2",
    driverId: null,
    pickupLocation: { latitude: 37.79825, longitude: -122.4324 },
    destination: { latitude: 37.78825, longitude: -122.4224 },
    status: "pending",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "3",
    userId: "user3",
    driverId: null,
    pickupLocation: { latitude: 37.779, longitude: -122.411 },
    destination: { latitude: 37.78825, longitude: -122.4224 },
    status: "pending",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "4",
    userId: "user4",
    driverId: null,
    pickupLocation: { latitude: 37.798, longitude: -122.432 },
    destination: { latitude: 37.788, longitude: -122.422 },
    status: "picked-up",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "5",
    userId: "user5",
    driverId: null,
    pickupLocation: { latitude: 37.788, longitude: -122.432 },
    destination: { latitude: 37.798, longitude: -122.422 },
    status: "accepted",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "6",
    userId: "user6",
    driverId: null,
    pickupLocation: { latitude: 37.758, longitude: -122.482 },
    destination: { latitude: 37.768, longitude: -122.472 },
    status: "declined",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
  {
    id: "7",
    userId: "user7",
    driverId: null,
    pickupLocation: { latitude: 37.718, longitude: -122.372 },
    destination: { latitude: 37.728, longitude: -122.362 },
    status: "dropped-off",
    pickupTime: new Date(),
    timestamp: new Date(),
  },
];

export default dummyRideRequests;
