// export const SET_DRIVER_LOCATION = "SET_DRIVER_LOCATION";
// export const SET_NEARBY_RIDE_REQUESTS = "SET_NEARBY_RIDE_REQUESTS";
// export const UPDATE_RIDE_REQUEST_STATUS = "UPDATE_RIDE_REQUEST_STATUS";
